
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/invoiceDB
    username: cacttus
    password: cacttus
  jpa:
    hibernate:
      ddl-auto: update


application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration-time: 86400000
